export const monitorDom = {
  form: document.getElementById("configForm"),
  feedback: document.getElementById("feedback"),
  modeText: document.getElementById("modeText"),
  startButton: document.getElementById("startButton"),
  addButton: document.getElementById("addButton"),
  removeButton: document.getElementById("removeButton"),
  stopButton: document.getElementById("stopButton"),
  logOutput: document.getElementById("logOutput"),
  windowGrid: document.getElementById("windowGrid"),
  manageConfirmBar: document.getElementById("manageConfirmBar"),
  headlinePanel: document.getElementById("headlinePanel"),
  overallHeadline: document.getElementById("overallHeadline"),
  overallSummary: document.getElementById("overallSummary"),
  overallStrongestSymbol: document.getElementById("overallStrongestSymbol"),
  overallWindow: document.getElementById("overallWindow"),
  overallPhase: document.getElementById("overallPhase"),
  versionInfo: document.getElementById("versionInfo"),
  symbolOverviewGrid: document.getElementById("symbolOverviewGrid"),
  selectedSymbolLabel: document.getElementById("selectedSymbolLabel"),
  manageSymbolsInput: document.getElementById("manageSymbols"),
  fields: {
    symbols: document.getElementById("symbols"),
    windowsMinutes: document.getElementById("windowsMinutes"),
    reportInterval: document.getElementById("reportInterval"),
    baselineMinutes: document.getElementById("baselineMinutes"),
    runtimeSeconds: document.getElementById("runtimeSeconds"),
  },
  summaryFields: {
    symbolCount: document.getElementById("summarySymbolCount"),
    readyCount: document.getElementById("summaryReadyCount"),
    strongestSymbol: document.getElementById("summaryStrongestSymbol"),
    strongestWindow: document.getElementById("summaryStrongestWindow"),
    updatedAt: document.getElementById("summaryUpdatedAt"),
  },
};
